### ISSUE TITLE
Error with creating a tournament

### ISSUE THREAD

**Issue by lakenoah17** [stefangeyer/challonge-java#12]
Hello there,

So I have been trying to use this library to develop an android app that can post to Challonge however, I don't really know what I'm doing wrong as I have copy and pasted the example from the wiki into my code and changed the fields appropriately but I keep getting this error.

Process: com.honorsmobileapps.noahshields.smashutilities, PID: 10392
    java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
        at at.stefangeyer.challonge.rest.retrofit.RetrofitRestClient.initialize(RetrofitRestClient.java:54)
        at at.stefangeyer.challonge.Challonge.<init>(Challonge.java:36)
        at com.honorsmobileapps.noahshields.smashutilities.TournamentFeatures.CreateTournamentActivity$3.run(CreateTournamentActivity.java:279)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoClassDefFoundError: Invalid descriptor: ex
    038.

If you can help that would be greatly appreciated however, I believe it might be that I am doing something wrong with my code. Thought I would check and ask and see if you maybe knew what this meant.

**Comment by stefangeyer** [comment]
Please provide snippets of the code that's causing trouble and the gradle dependency imports so I can check if you are doing something wrong.

**Comment by lakenoah17** [comment]
Hey I'm sorry I just figured it out. It was a gradle dependency problem. I was using the wrong dependencies.
