### ISSUE TITLE
Missing "ACCEPTING_PREDICTIONS" tournament state

### ISSUE THREAD

**Issue by gpluscb** [stefangeyer/challonge-java#13]
The internal deserialization of a tournament which is accepting bracket prediction fails because the corresponding TournamentState is missing:
```
try {
	challonge.getTournament("f3m4rmna");
} catch(Exception e) {
	e.printStackTrace();
}
```
Catches the following exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant at.stefangeyer.challonge.model.enumeration.TournamentState.ACCEPTING_PREDICTIONS
	at java.lang.Enum.valueOf(Enum.java:238)
	at at.stefangeyer.challonge.model.enumeration.TournamentState.valueOf(TournamentState.java:3)
	at at.stefangeyer.challonge.serializer.gson.adapter.TournamentAdapter.deserialize(TournamentAdapter.java:78)
	at at.stefangeyer.challonge.serializer.gson.adapter.TournamentAdapter.deserialize(TournamentAdapter.java:22)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at at.stefangeyer.challonge.serializer.gson.GsonSerializer.deserialize(GsonSerializer.java:63)
	at at.stefangeyer.challonge.rest.retrofit.converter.RetrofitResponseBodyConverter.convert(RetrofitResponseBodyConverter.java:24)
	at at.stefangeyer.challonge.rest.retrofit.converter.RetrofitResponseBodyConverter.convert(RetrofitResponseBodyConverter.java:10)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
	at at.stefangeyer.challonge.rest.retrofit.RetrofitTournamentRestClient.getTournament(RetrofitTournamentRestClient.java:62)
	at at.stefangeyer.challonge.service.implementation.SimpleTournamentService.getTournament(SimpleTournamentService.java:49)
	at at.stefangeyer.challonge.Challonge.getTournament(Challonge.java:71)
	at at.stefangeyer.challonge.Challonge.getTournament(Challonge.java:75)
	at challonge_test.Main.main(Main.java:18)
```

**Comment by stefangeyer** [comment]
The bug you encountered should be fixed. The fix will be available with the next release. I created a snapshot build for now available on maven central under `3.0.0-SNAPSHOT`. Just a heads up: the project sructure has changed a bit as of now. I will update the code example when the new version is ready but it shouldnt be too hard to figure out anyway. If you have any questions feel free to ask.

**Comment by gpluscb** [comment]
Should the snapshot already be online? My build.gradle says it "Could not resolve: at.stefangeyer.challonge:core:3.0.0-SNAPSHOT" and I can't find it on https://mvnrepository.com either.

**Comment by stefangeyer** [comment]
Sorry, i meant the OSSRH snapshot repository. Since its a snapshot only, it will obviously not be available on maven central. Available [here](https://oss.sonatype.org/content/groups/public/).

**Comment by gpluscb** [comment]
Thanks, everything seems to work now.
