### ISSUE TITLE
Issues with Gson and Retrofit

### ISSUE THREAD

**Issue by blok601** [stefangeyer/challonge-java#9]
`null
org.bukkit.command.CommandException: Unhandled exception executing command 'tournament' in plugin Tournament v1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalAccessError: tried to access method com.google.gson.Gson.newJsonWriter(Ljava/io/Writer;)Lcom/google/gson/stream/JsonWriter; from class retrofit2.converter.gson.GsonRequestBodyConverter
        at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:45) ~[?:?]
        at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:30) ~[?:?]
        at retrofit2.ParameterHandler$Body.apply(ParameterHandler.java:297) ~[?:?]
        at retrofit2.ServiceMethod.toRequest(ServiceMethod.java:109) ~[?:?]
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:178) ~[?:?]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:162) ~[?:?]
        at com.exsoloscript.challonge.handler.call.RetrofitChallongeApiCall.sync(RetrofitChallongeApiCall.java:60) ~[?:?]
        at com.nightshadepvp.tournament.command.run.TournamentCommand.onCommand(TournamentCommand.java:71) ~[?:?]
        at com.nightshadepvp.tournament.Tournament.onCommand(Tournament.java:111) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        ... 15 more
`

Got that error when running 

`Tournament.getInstance().getApi().tournaments().createTournament(query).sync()`

**Comment by blok601** [comment]
Sorry about the formatting here is the error:

`Caused by: java.lang.IllegalAccessError: tried to access method com.google.gson.Gson.newJsonWriter(Ljava/io/Writer;)Lcom/google/gson/stream/JsonWriter; from class retrofit2.converter.gson.GsonRequestBodyConverter
	at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:45) ~[?:?]
	at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:30) ~[?:?]
	at retrofit2.ParameterHandler$Body.apply(ParameterHandler.java:297) ~[?:?]
	at retrofit2.ServiceMethod.toRequest(ServiceMethod.java:109) ~[?:?]
	at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:178) ~[?:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:162) ~[?:?]
	at com.exsoloscript.challonge.handler.call.RetrofitChallongeApiCall.sync(RetrofitChallongeApiCall.java:60) ~[?:?]
	at com.nightshadepvp.tournament.command.run.TournamentCommand.onCommand(TournamentCommand.java:71) ~[?:?]
	at com.nightshadepvp.tournament.Tournament.onCommand(Tournament.java:111) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 15 more`

**Comment by stefangeyer** [comment]
I'll leave [this](https://stackoverflow.com/a/48316828) stackoverflow response here, as it describes perfectly why this error occurs at runtime. It is probably a Gson version mismatch. One of your other dependencies might require a different version of Gson. I hope this helps.

**Comment by stefangeyer** [comment]
Since the new version was released, this problem is probably no longer relevant. Feel free to comment if there are still any issues.
